[theme]
name = "gruvbox-dark"
[theme.overrides]
good_bg = "#009900"

[icons]
name = "awesome"

[[block]]
block = "custom"
interval = 300
command = 'cat /home/thing/Documents/account'

[[block]]
block = "battery"
interval=10
format = "{percentage}% {time}"

[[block]]
block = "net"
device = "wlp59s0"
ssid = true
ip = true
speed_up = false
speed_down = false
interval = 5


[[block]]
block = "net"
device = "ens1u2u4"
ip = true
speed_up = true
speed_down = true
interval = 1

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 60
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug} G"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
collapsed = true
interval = 5
format = "{min}° min, {max}° max, {average}° avg"
chip = "*-isa-*"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
